name: Notify API on Reviewer Assignment

on:
  pull_request_reviewers:
    types: 
      - assigned
      - unassigned

jobs:
  notify-api:
    runs-on: ubuntu-latest

    steps:
    - name: Call API when reviewer is assigned or changed
      run: |
        curl -X POST https://l6ejodsiu3.execute-api.ap-northeast-2.amazonaws.com/test/pull-request \
        -H "Content-Type: application/json" \
        -d '{
          "repository": "${{ github.repository }}",
          "pull_request": "${{ github.event.pull_request.number }}",
          "pull_request": "${{ github.event.pull_request._link.self }}",
          "reviewer": "${{ github.event.requested_reviewer }}",
          "action": "${{ github.event.action }}"
        }'
