name: PR Review Notification

on:
  pull_request:
    types: [edited, review_requested]

jobs:
  notify:
    runs-on: [ubuntu-latest]
    steps:
      - name: PR Review Notification
        uses: oris-8/notification-pr-review@v1.0.1
        with:
          image_url : "https://github.com/user-attachments/assets/23ca5221-eced-471d-9525-4cdd8c18536a"
          webhook_url: "https://discord.com/api/webhooks/1288113487343779900/-3kKkzQOKSweaOV6XnR2v9_IFznmPSnsHPOC3O_87qwbeFPzzklzahlbnxxqr4L62L-W"
          user_table: ${{vars.USER_TABLE}}
